packages:
  - apps/*
  - packages/*

allowBuilds:
  esbuild: true
  lightningcss: true

minimumReleaseAgeExclude:
  - '@radix-ui/react-accordion@1.2.21'
  - '@radix-ui/react-arrow@1.1.16'
  - '@radix-ui/react-avatar@1.2.7'
  - '@radix-ui/react-checkbox@1.3.12'
  - '@radix-ui/react-collapsible@1.1.21'
  - '@radix-ui/react-collection@1.1.16'
  - '@radix-ui/react-dialog@1.2.0'
  - '@radix-ui/react-direction@1.1.5'
  - '@radix-ui/react-dismissable-layer@1.1.20'
  - '@radix-ui/react-dropdown-menu@2.1.25'
  - '@radix-ui/react-focus-scope@1.2.0'
  - '@radix-ui/react-menu@2.1.25'
  - '@radix-ui/react-popover@1.2.0'
  - '@radix-ui/react-popper@1.3.8'
  - '@radix-ui/react-portal@1.1.18'
  - '@radix-ui/react-presence@1.1.11'
  - '@radix-ui/react-primitive@2.1.11'
  - '@radix-ui/react-progress@1.1.17'
  - '@radix-ui/react-radio-group@1.4.8'
  - '@radix-ui/react-roving-focus@1.1.20'
  - '@radix-ui/react-select@2.3.8'
  - '@radix-ui/react-separator@1.1.16'
  - '@radix-ui/react-slider@1.5.0'
  - '@radix-ui/react-slot@1.4.0'
  - '@radix-ui/react-switch@1.3.8'
  - '@radix-ui/react-tabs@1.1.22'
  - '@radix-ui/react-toast@1.2.24'
  - '@radix-ui/react-tooltip@1.3.0'
  - '@radix-ui/react-use-size@1.1.5'
  - '@radix-ui/react-visually-hidden@1.2.12'
