/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComponentsRouteRouteImport } from './routes/components/route'
import { Route as GuideRouteRouteImport } from './routes/guide/route'
import { Route as ComponentsIndexRouteImport } from './routes/components/index'
import { Route as ComponentsAccordionRouteImport } from './routes/components/accordion'
import { Route as ComponentsAlertRouteImport } from './routes/components/alert'
import { Route as ComponentsAspectRatioRouteImport } from './routes/components/aspect-ratio'
import { Route as ComponentsAvatarRouteImport } from './routes/components/avatar'
import { Route as ComponentsBadgeRouteImport } from './routes/components/badge'
import { Route as ComponentsButtonRouteImport } from './routes/components/button'
import { Route as ComponentsCardRouteImport } from './routes/components/card'
import { Route as ComponentsCarouselRouteImport } from './routes/components/carousel'
import { Route as ComponentsCenterRouteImport } from './routes/components/center'
import { Route as ComponentsCheckboxRouteImport } from './routes/components/checkbox'
import { Route as ComponentsClusterRouteImport } from './routes/components/cluster'
import { Route as ComponentsCollapsibleRouteImport } from './routes/components/collapsible'
import { Route as ComponentsCommandRouteImport } from './routes/components/command'
import { Route as ComponentsContainerRouteImport } from './routes/components/container'
import { Route as ComponentsDialogRouteImport } from './routes/components/dialog'
import { Route as ComponentsDropdownMenuRouteImport } from './routes/components/dropdown-menu'
import { Route as ComponentsFieldRouteImport } from './routes/components/field'
import { Route as ComponentsGridRouteImport } from './routes/components/grid'
import { Route as ComponentsHoverCardRouteImport } from './routes/components/hover-card'
import { Route as ComponentsInputRouteImport } from './routes/components/input'
import { Route as ComponentsLabelRouteImport } from './routes/components/label'
import { Route as ComponentsPopoverRouteImport } from './routes/components/popover'
import { Route as ComponentsProgressRouteImport } from './routes/components/progress'
import { Route as ComponentsRadioGroupRouteImport } from './routes/components/radio-group'
import { Route as ComponentsSectionRouteImport } from './routes/components/section'
import { Route as ComponentsSelectRouteImport } from './routes/components/select'
import { Route as ComponentsSeparatorRouteImport } from './routes/components/separator'
import { Route as ComponentsSkeletonRouteImport } from './routes/components/skeleton'
import { Route as ComponentsSpacerRouteImport } from './routes/components/spacer'
import { Route as ComponentsSplitRouteImport } from './routes/components/split'
import { Route as ComponentsStackRouteImport } from './routes/components/stack'
import { Route as ComponentsSwitchRouteImport } from './routes/components/switch'
import { Route as ComponentsTableRouteImport } from './routes/components/table'
import { Route as ComponentsTabsRouteImport } from './routes/components/tabs'
import { Route as ComponentsTextareaRouteImport } from './routes/components/textarea'
import { Route as ComponentsToastRouteImport } from './routes/components/toast'
import { Route as ComponentsTooltipRouteImport } from './routes/components/tooltip'
import { Route as GuideIndexRouteImport } from './routes/guide/index'
import { Route as GuideCliRouteImport } from './routes/guide/cli'
import { Route as GuideGettingStartedRouteImport } from './routes/guide/getting-started'
import { Route as GuideInstallationRouteImport } from './routes/guide/installation'
import { Route as GuideThemingRouteImport } from './routes/guide/theming'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsRouteRoute = ComponentsRouteRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRouteRoute = GuideRouteRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsIndexRoute = ComponentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ComponentsRouteRoute,
} as any)
const ComponentsAccordionRoute = ComponentsAccordionRouteImport.update({
  id: '/accordion',
  path: '/accordion',
  getParentRoute: () => ComponentsRouteRoute,
} as any)
const ComponentsAlertRoute = ComponentsAlertRouteImport.update({
  id: '/alert',
  path: '/alert',
  getParentRoute: () => ComponentsRouteRoute,
} as any)
const ComponentsAspectRatioRoute = ComponentsAspectRatioRouteImport.update({
  id: '/aspect-ratio',
  path: '/aspect-ratio',
  getParentRoute: () => ComponentsRouteRoute,
} as any)
const ComponentsAvatarRoute = ComponentsAvatarRouteImport.update({
  id: '/avatar',
  path: '/avatar',
  getParentRoute: () => ComponentsRouteRoute,
} as any)
const ComponentsBadgeRoute = ComponentsBadgeRouteImport.update({
  id: '/badge',
  path: '/badge',
  getParentRoute: () => ComponentsRouteRoute,
} as any)
const ComponentsButtonRoute = ComponentsButtonRouteImport.update({
  id: '/button',
  path: '/button',
  getParentRoute: () => ComponentsRouteRoute,
} as any)
const ComponentsCardRoute = ComponentsCardRouteImport.update({
  id: '/card',
  path: '/card',
  getParentRoute: () => ComponentsRouteRoute,
} as any)
const ComponentsCarouselRoute = ComponentsCarouselRouteImport.update({
  id: '/carousel',
  path: '/carousel',
  getParentRoute: () => ComponentsRouteRoute,
} as any)
const ComponentsCenterRoute = ComponentsCenterRouteImport.update({
  id: '/center',
  path: '/center',
  getParentRoute: () => ComponentsRouteRoute,
} as any)
const ComponentsCheckboxRoute = ComponentsCheckboxRouteImport.update({
  id: '/checkbox',
  path: '/checkbox',
  getParentRoute: () => ComponentsRouteRoute,
} as any)
const ComponentsClusterRoute = ComponentsClusterRouteImport.update({
  id: '/cluster',
  path: '/cluster',
  getParentRoute: () => ComponentsRouteRoute,
} as any)
const ComponentsCollapsibleRoute = ComponentsCollapsibleRouteImport.update({
  id: '/collapsible',
  path: '/collapsible',
  getParentRoute: () => ComponentsRouteRoute,
} as any)
const ComponentsCommandRoute = ComponentsCommandRouteImport.update({
  id: '/command',
  path: '/command',
  getParentRoute: () => ComponentsRouteRoute,
} as any)
const ComponentsContainerRoute = ComponentsContainerRouteImport.update({
  id: '/container',
  path: '/container',
  getParentRoute: () => ComponentsRouteRoute,
} as any)
const ComponentsDialogRoute = ComponentsDialogRouteImport.update({
  id: '/dialog',
  path: '/dialog',
  getParentRoute: () => ComponentsRouteRoute,
} as any)
const ComponentsDropdownMenuRoute = ComponentsDropdownMenuRouteImport.update({
  id: '/dropdown-menu',
  path: '/dropdown-menu',
  getParentRoute: () => ComponentsRouteRoute,
} as any)
const ComponentsFieldRoute = ComponentsFieldRouteImport.update({
  id: '/field',
  path: '/field',
  getParentRoute: () => ComponentsRouteRoute,
} as any)
const ComponentsGridRoute = ComponentsGridRouteImport.update({
  id: '/grid',
  path: '/grid',
  getParentRoute: () => ComponentsRouteRoute,
} as any)
const ComponentsHoverCardRoute = ComponentsHoverCardRouteImport.update({
  id: '/hover-card',
  path: '/hover-card',
  getParentRoute: () => ComponentsRouteRoute,
} as any)
const ComponentsInputRoute = ComponentsInputRouteImport.update({
  id: '/input',
  path: '/input',
  getParentRoute: () => ComponentsRouteRoute,
} as any)
const ComponentsLabelRoute = ComponentsLabelRouteImport.update({
  id: '/label',
  path: '/label',
  getParentRoute: () => ComponentsRouteRoute,
} as any)
const ComponentsPopoverRoute = ComponentsPopoverRouteImport.update({
  id: '/popover',
  path: '/popover',
  getParentRoute: () => ComponentsRouteRoute,
} as any)
const ComponentsProgressRoute = ComponentsProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => ComponentsRouteRoute,
} as any)
const ComponentsRadioGroupRoute = ComponentsRadioGroupRouteImport.update({
  id: '/radio-group',
  path: '/radio-group',
  getParentRoute: () => ComponentsRouteRoute,
} as any)
const ComponentsSectionRoute = ComponentsSectionRouteImport.update({
  id: '/section',
  path: '/section',
  getParentRoute: () => ComponentsRouteRoute,
} as any)
const ComponentsSelectRoute = ComponentsSelectRouteImport.update({
  id: '/select',
  path: '/select',
  getParentRoute: () => ComponentsRouteRoute,
} as any)
const ComponentsSeparatorRoute = ComponentsSeparatorRouteImport.update({
  id: '/separator',
  path: '/separator',
  getParentRoute: () => ComponentsRouteRoute,
} as any)
const ComponentsSkeletonRoute = ComponentsSkeletonRouteImport.update({
  id: '/skeleton',
  path: '/skeleton',
  getParentRoute: () => ComponentsRouteRoute,
} as any)
const ComponentsSpacerRoute = ComponentsSpacerRouteImport.update({
  id: '/spacer',
  path: '/spacer',
  getParentRoute: () => ComponentsRouteRoute,
} as any)
const ComponentsSplitRoute = ComponentsSplitRouteImport.update({
  id: '/split',
  path: '/split',
  getParentRoute: () => ComponentsRouteRoute,
} as any)
const ComponentsStackRoute = ComponentsStackRouteImport.update({
  id: '/stack',
  path: '/stack',
  getParentRoute: () => ComponentsRouteRoute,
} as any)
const ComponentsSwitchRoute = ComponentsSwitchRouteImport.update({
  id: '/switch',
  path: '/switch',
  getParentRoute: () => ComponentsRouteRoute,
} as any)
const ComponentsTableRoute = ComponentsTableRouteImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => ComponentsRouteRoute,
} as any)
const ComponentsTabsRoute = ComponentsTabsRouteImport.update({
  id: '/tabs',
  path: '/tabs',
  getParentRoute: () => ComponentsRouteRoute,
} as any)
const ComponentsTextareaRoute = ComponentsTextareaRouteImport.update({
  id: '/textarea',
  path: '/textarea',
  getParentRoute: () => ComponentsRouteRoute,
} as any)
const ComponentsToastRoute = ComponentsToastRouteImport.update({
  id: '/toast',
  path: '/toast',
  getParentRoute: () => ComponentsRouteRoute,
} as any)
const ComponentsTooltipRoute = ComponentsTooltipRouteImport.update({
  id: '/tooltip',
  path: '/tooltip',
  getParentRoute: () => ComponentsRouteRoute,
} as any)
const GuideIndexRoute = GuideIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GuideRouteRoute,
} as any)
const GuideCliRoute = GuideCliRouteImport.update({
  id: '/cli',
  path: '/cli',
  getParentRoute: () => GuideRouteRoute,
} as any)
const GuideGettingStartedRoute = GuideGettingStartedRouteImport.update({
  id: '/getting-started',
  path: '/getting-started',
  getParentRoute: () => GuideRouteRoute,
} as any)
const GuideInstallationRoute = GuideInstallationRouteImport.update({
  id: '/installation',
  path: '/installation',
  getParentRoute: () => GuideRouteRoute,
} as any)
const GuideThemingRoute = GuideThemingRouteImport.update({
  id: '/theming',
  path: '/theming',
  getParentRoute: () => GuideRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/components': typeof ComponentsRouteRouteWithChildren
  '/guide': typeof GuideRouteRouteWithChildren
  '/components/accordion': typeof ComponentsAccordionRoute
  '/components/alert': typeof ComponentsAlertRoute
  '/components/aspect-ratio': typeof ComponentsAspectRatioRoute
  '/components/avatar': typeof ComponentsAvatarRoute
  '/components/badge': typeof ComponentsBadgeRoute
  '/components/button': typeof ComponentsButtonRoute
  '/components/card': typeof ComponentsCardRoute
  '/components/carousel': typeof ComponentsCarouselRoute
  '/components/center': typeof ComponentsCenterRoute
  '/components/checkbox': typeof ComponentsCheckboxRoute
  '/components/cluster': typeof ComponentsClusterRoute
  '/components/collapsible': typeof ComponentsCollapsibleRoute
  '/components/command': typeof ComponentsCommandRoute
  '/components/container': typeof ComponentsContainerRoute
  '/components/dialog': typeof ComponentsDialogRoute
  '/components/dropdown-menu': typeof ComponentsDropdownMenuRoute
  '/components/field': typeof ComponentsFieldRoute
  '/components/grid': typeof ComponentsGridRoute
  '/components/hover-card': typeof ComponentsHoverCardRoute
  '/components/input': typeof ComponentsInputRoute
  '/components/label': typeof ComponentsLabelRoute
  '/components/popover': typeof ComponentsPopoverRoute
  '/components/progress': typeof ComponentsProgressRoute
  '/components/radio-group': typeof ComponentsRadioGroupRoute
  '/components/section': typeof ComponentsSectionRoute
  '/components/select': typeof ComponentsSelectRoute
  '/components/separator': typeof ComponentsSeparatorRoute
  '/components/skeleton': typeof ComponentsSkeletonRoute
  '/components/spacer': typeof ComponentsSpacerRoute
  '/components/split': typeof ComponentsSplitRoute
  '/components/stack': typeof ComponentsStackRoute
  '/components/switch': typeof ComponentsSwitchRoute
  '/components/table': typeof ComponentsTableRoute
  '/components/tabs': typeof ComponentsTabsRoute
  '/components/textarea': typeof ComponentsTextareaRoute
  '/components/toast': typeof ComponentsToastRoute
  '/components/tooltip': typeof ComponentsTooltipRoute
  '/guide/cli': typeof GuideCliRoute
  '/guide/getting-started': typeof GuideGettingStartedRoute
  '/guide/installation': typeof GuideInstallationRoute
  '/guide/theming': typeof GuideThemingRoute
  '/components/': typeof ComponentsIndexRoute
  '/guide/': typeof GuideIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/components/accordion': typeof ComponentsAccordionRoute
  '/components/alert': typeof ComponentsAlertRoute
  '/components/aspect-ratio': typeof ComponentsAspectRatioRoute
  '/components/avatar': typeof ComponentsAvatarRoute
  '/components/badge': typeof ComponentsBadgeRoute
  '/components/button': typeof ComponentsButtonRoute
  '/components/card': typeof ComponentsCardRoute
  '/components/carousel': typeof ComponentsCarouselRoute
  '/components/center': typeof ComponentsCenterRoute
  '/components/checkbox': typeof ComponentsCheckboxRoute
  '/components/cluster': typeof ComponentsClusterRoute
  '/components/collapsible': typeof ComponentsCollapsibleRoute
  '/components/command': typeof ComponentsCommandRoute
  '/components/container': typeof ComponentsContainerRoute
  '/components/dialog': typeof ComponentsDialogRoute
  '/components/dropdown-menu': typeof ComponentsDropdownMenuRoute
  '/components/field': typeof ComponentsFieldRoute
  '/components/grid': typeof ComponentsGridRoute
  '/components/hover-card': typeof ComponentsHoverCardRoute
  '/components/input': typeof ComponentsInputRoute
  '/components/label': typeof ComponentsLabelRoute
  '/components/popover': typeof ComponentsPopoverRoute
  '/components/progress': typeof ComponentsProgressRoute
  '/components/radio-group': typeof ComponentsRadioGroupRoute
  '/components/section': typeof ComponentsSectionRoute
  '/components/select': typeof ComponentsSelectRoute
  '/components/separator': typeof ComponentsSeparatorRoute
  '/components/skeleton': typeof ComponentsSkeletonRoute
  '/components/spacer': typeof ComponentsSpacerRoute
  '/components/split': typeof ComponentsSplitRoute
  '/components/stack': typeof ComponentsStackRoute
  '/components/switch': typeof ComponentsSwitchRoute
  '/components/table': typeof ComponentsTableRoute
  '/components/tabs': typeof ComponentsTabsRoute
  '/components/textarea': typeof ComponentsTextareaRoute
  '/components/toast': typeof ComponentsToastRoute
  '/components/tooltip': typeof ComponentsTooltipRoute
  '/guide/cli': typeof GuideCliRoute
  '/guide/getting-started': typeof GuideGettingStartedRoute
  '/guide/installation': typeof GuideInstallationRoute
  '/guide/theming': typeof GuideThemingRoute
  '/components': typeof ComponentsIndexRoute
  '/guide': typeof GuideIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/components': typeof ComponentsRouteRouteWithChildren
  '/guide': typeof GuideRouteRouteWithChildren
  '/components/accordion': typeof ComponentsAccordionRoute
  '/components/alert': typeof ComponentsAlertRoute
  '/components/aspect-ratio': typeof ComponentsAspectRatioRoute
  '/components/avatar': typeof ComponentsAvatarRoute
  '/components/badge': typeof ComponentsBadgeRoute
  '/components/button': typeof ComponentsButtonRoute
  '/components/card': typeof ComponentsCardRoute
  '/components/carousel': typeof ComponentsCarouselRoute
  '/components/center': typeof ComponentsCenterRoute
  '/components/checkbox': typeof ComponentsCheckboxRoute
  '/components/cluster': typeof ComponentsClusterRoute
  '/components/collapsible': typeof ComponentsCollapsibleRoute
  '/components/command': typeof ComponentsCommandRoute
  '/components/container': typeof ComponentsContainerRoute
  '/components/dialog': typeof ComponentsDialogRoute
  '/components/dropdown-menu': typeof ComponentsDropdownMenuRoute
  '/components/field': typeof ComponentsFieldRoute
  '/components/grid': typeof ComponentsGridRoute
  '/components/hover-card': typeof ComponentsHoverCardRoute
  '/components/input': typeof ComponentsInputRoute
  '/components/label': typeof ComponentsLabelRoute
  '/components/popover': typeof ComponentsPopoverRoute
  '/components/progress': typeof ComponentsProgressRoute
  '/components/radio-group': typeof ComponentsRadioGroupRoute
  '/components/section': typeof ComponentsSectionRoute
  '/components/select': typeof ComponentsSelectRoute
  '/components/separator': typeof ComponentsSeparatorRoute
  '/components/skeleton': typeof ComponentsSkeletonRoute
  '/components/spacer': typeof ComponentsSpacerRoute
  '/components/split': typeof ComponentsSplitRoute
  '/components/stack': typeof ComponentsStackRoute
  '/components/switch': typeof ComponentsSwitchRoute
  '/components/table': typeof ComponentsTableRoute
  '/components/tabs': typeof ComponentsTabsRoute
  '/components/textarea': typeof ComponentsTextareaRoute
  '/components/toast': typeof ComponentsToastRoute
  '/components/tooltip': typeof ComponentsTooltipRoute
  '/guide/cli': typeof GuideCliRoute
  '/guide/getting-started': typeof GuideGettingStartedRoute
  '/guide/installation': typeof GuideInstallationRoute
  '/guide/theming': typeof GuideThemingRoute
  '/components/': typeof ComponentsIndexRoute
  '/guide/': typeof GuideIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/components'
    | '/guide'
    | '/components/accordion'
    | '/components/alert'
    | '/components/aspect-ratio'
    | '/components/avatar'
    | '/components/badge'
    | '/components/button'
    | '/components/card'
    | '/components/carousel'
    | '/components/center'
    | '/components/checkbox'
    | '/components/cluster'
    | '/components/collapsible'
    | '/components/command'
    | '/components/container'
    | '/components/dialog'
    | '/components/dropdown-menu'
    | '/components/field'
    | '/components/grid'
    | '/components/hover-card'
    | '/components/input'
    | '/components/label'
    | '/components/popover'
    | '/components/progress'
    | '/components/radio-group'
    | '/components/section'
    | '/components/select'
    | '/components/separator'
    | '/components/skeleton'
    | '/components/spacer'
    | '/components/split'
    | '/components/stack'
    | '/components/switch'
    | '/components/table'
    | '/components/tabs'
    | '/components/textarea'
    | '/components/toast'
    | '/components/tooltip'
    | '/guide/cli'
    | '/guide/getting-started'
    | '/guide/installation'
    | '/guide/theming'
    | '/components/'
    | '/guide/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/components/accordion'
    | '/components/alert'
    | '/components/aspect-ratio'
    | '/components/avatar'
    | '/components/badge'
    | '/components/button'
    | '/components/card'
    | '/components/carousel'
    | '/components/center'
    | '/components/checkbox'
    | '/components/cluster'
    | '/components/collapsible'
    | '/components/command'
    | '/components/container'
    | '/components/dialog'
    | '/components/dropdown-menu'
    | '/components/field'
    | '/components/grid'
    | '/components/hover-card'
    | '/components/input'
    | '/components/label'
    | '/components/popover'
    | '/components/progress'
    | '/components/radio-group'
    | '/components/section'
    | '/components/select'
    | '/components/separator'
    | '/components/skeleton'
    | '/components/spacer'
    | '/components/split'
    | '/components/stack'
    | '/components/switch'
    | '/components/table'
    | '/components/tabs'
    | '/components/textarea'
    | '/components/toast'
    | '/components/tooltip'
    | '/guide/cli'
    | '/guide/getting-started'
    | '/guide/installation'
    | '/guide/theming'
    | '/components'
    | '/guide'
  id:
    | '__root__'
    | '/'
    | '/components'
    | '/guide'
    | '/components/accordion'
    | '/components/alert'
    | '/components/aspect-ratio'
    | '/components/avatar'
    | '/components/badge'
    | '/components/button'
    | '/components/card'
    | '/components/carousel'
    | '/components/center'
    | '/components/checkbox'
    | '/components/cluster'
    | '/components/collapsible'
    | '/components/command'
    | '/components/container'
    | '/components/dialog'
    | '/components/dropdown-menu'
    | '/components/field'
    | '/components/grid'
    | '/components/hover-card'
    | '/components/input'
    | '/components/label'
    | '/components/popover'
    | '/components/progress'
    | '/components/radio-group'
    | '/components/section'
    | '/components/select'
    | '/components/separator'
    | '/components/skeleton'
    | '/components/spacer'
    | '/components/split'
    | '/components/stack'
    | '/components/switch'
    | '/components/table'
    | '/components/tabs'
    | '/components/textarea'
    | '/components/toast'
    | '/components/tooltip'
    | '/guide/cli'
    | '/guide/getting-started'
    | '/guide/installation'
    | '/guide/theming'
    | '/components/'
    | '/guide/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComponentsRouteRoute: typeof ComponentsRouteRouteWithChildren
  GuideRouteRoute: typeof GuideRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components': {
      id: '/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/': {
      id: '/components/'
      path: '/'
      fullPath: '/components/'
      preLoaderRoute: typeof ComponentsIndexRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/accordion': {
      id: '/components/accordion'
      path: '/accordion'
      fullPath: '/components/accordion'
      preLoaderRoute: typeof ComponentsAccordionRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/alert': {
      id: '/components/alert'
      path: '/alert'
      fullPath: '/components/alert'
      preLoaderRoute: typeof ComponentsAlertRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/aspect-ratio': {
      id: '/components/aspect-ratio'
      path: '/aspect-ratio'
      fullPath: '/components/aspect-ratio'
      preLoaderRoute: typeof ComponentsAspectRatioRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/avatar': {
      id: '/components/avatar'
      path: '/avatar'
      fullPath: '/components/avatar'
      preLoaderRoute: typeof ComponentsAvatarRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/badge': {
      id: '/components/badge'
      path: '/badge'
      fullPath: '/components/badge'
      preLoaderRoute: typeof ComponentsBadgeRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/button': {
      id: '/components/button'
      path: '/button'
      fullPath: '/components/button'
      preLoaderRoute: typeof ComponentsButtonRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/card': {
      id: '/components/card'
      path: '/card'
      fullPath: '/components/card'
      preLoaderRoute: typeof ComponentsCardRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/carousel': {
      id: '/components/carousel'
      path: '/carousel'
      fullPath: '/components/carousel'
      preLoaderRoute: typeof ComponentsCarouselRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/center': {
      id: '/components/center'
      path: '/center'
      fullPath: '/components/center'
      preLoaderRoute: typeof ComponentsCenterRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/checkbox': {
      id: '/components/checkbox'
      path: '/checkbox'
      fullPath: '/components/checkbox'
      preLoaderRoute: typeof ComponentsCheckboxRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/cluster': {
      id: '/components/cluster'
      path: '/cluster'
      fullPath: '/components/cluster'
      preLoaderRoute: typeof ComponentsClusterRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/collapsible': {
      id: '/components/collapsible'
      path: '/collapsible'
      fullPath: '/components/collapsible'
      preLoaderRoute: typeof ComponentsCollapsibleRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/command': {
      id: '/components/command'
      path: '/command'
      fullPath: '/components/command'
      preLoaderRoute: typeof ComponentsCommandRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/container': {
      id: '/components/container'
      path: '/container'
      fullPath: '/components/container'
      preLoaderRoute: typeof ComponentsContainerRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/dialog': {
      id: '/components/dialog'
      path: '/dialog'
      fullPath: '/components/dialog'
      preLoaderRoute: typeof ComponentsDialogRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/dropdown-menu': {
      id: '/components/dropdown-menu'
      path: '/dropdown-menu'
      fullPath: '/components/dropdown-menu'
      preLoaderRoute: typeof ComponentsDropdownMenuRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/field': {
      id: '/components/field'
      path: '/field'
      fullPath: '/components/field'
      preLoaderRoute: typeof ComponentsFieldRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/grid': {
      id: '/components/grid'
      path: '/grid'
      fullPath: '/components/grid'
      preLoaderRoute: typeof ComponentsGridRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/hover-card': {
      id: '/components/hover-card'
      path: '/hover-card'
      fullPath: '/components/hover-card'
      preLoaderRoute: typeof ComponentsHoverCardRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/input': {
      id: '/components/input'
      path: '/input'
      fullPath: '/components/input'
      preLoaderRoute: typeof ComponentsInputRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/label': {
      id: '/components/label'
      path: '/label'
      fullPath: '/components/label'
      preLoaderRoute: typeof ComponentsLabelRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/popover': {
      id: '/components/popover'
      path: '/popover'
      fullPath: '/components/popover'
      preLoaderRoute: typeof ComponentsPopoverRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/progress': {
      id: '/components/progress'
      path: '/progress'
      fullPath: '/components/progress'
      preLoaderRoute: typeof ComponentsProgressRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/radio-group': {
      id: '/components/radio-group'
      path: '/radio-group'
      fullPath: '/components/radio-group'
      preLoaderRoute: typeof ComponentsRadioGroupRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/section': {
      id: '/components/section'
      path: '/section'
      fullPath: '/components/section'
      preLoaderRoute: typeof ComponentsSectionRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/select': {
      id: '/components/select'
      path: '/select'
      fullPath: '/components/select'
      preLoaderRoute: typeof ComponentsSelectRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/separator': {
      id: '/components/separator'
      path: '/separator'
      fullPath: '/components/separator'
      preLoaderRoute: typeof ComponentsSeparatorRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/skeleton': {
      id: '/components/skeleton'
      path: '/skeleton'
      fullPath: '/components/skeleton'
      preLoaderRoute: typeof ComponentsSkeletonRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/spacer': {
      id: '/components/spacer'
      path: '/spacer'
      fullPath: '/components/spacer'
      preLoaderRoute: typeof ComponentsSpacerRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/split': {
      id: '/components/split'
      path: '/split'
      fullPath: '/components/split'
      preLoaderRoute: typeof ComponentsSplitRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/stack': {
      id: '/components/stack'
      path: '/stack'
      fullPath: '/components/stack'
      preLoaderRoute: typeof ComponentsStackRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/switch': {
      id: '/components/switch'
      path: '/switch'
      fullPath: '/components/switch'
      preLoaderRoute: typeof ComponentsSwitchRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/table': {
      id: '/components/table'
      path: '/table'
      fullPath: '/components/table'
      preLoaderRoute: typeof ComponentsTableRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/tabs': {
      id: '/components/tabs'
      path: '/tabs'
      fullPath: '/components/tabs'
      preLoaderRoute: typeof ComponentsTabsRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/textarea': {
      id: '/components/textarea'
      path: '/textarea'
      fullPath: '/components/textarea'
      preLoaderRoute: typeof ComponentsTextareaRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/toast': {
      id: '/components/toast'
      path: '/toast'
      fullPath: '/components/toast'
      preLoaderRoute: typeof ComponentsToastRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/tooltip': {
      id: '/components/tooltip'
      path: '/tooltip'
      fullPath: '/components/tooltip'
      preLoaderRoute: typeof ComponentsTooltipRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/guide/': {
      id: '/guide/'
      path: '/'
      fullPath: '/guide/'
      preLoaderRoute: typeof GuideIndexRouteImport
      parentRoute: typeof GuideRouteRoute
    }
    '/guide/cli': {
      id: '/guide/cli'
      path: '/cli'
      fullPath: '/guide/cli'
      preLoaderRoute: typeof GuideCliRouteImport
      parentRoute: typeof GuideRouteRoute
    }
    '/guide/getting-started': {
      id: '/guide/getting-started'
      path: '/getting-started'
      fullPath: '/guide/getting-started'
      preLoaderRoute: typeof GuideGettingStartedRouteImport
      parentRoute: typeof GuideRouteRoute
    }
    '/guide/installation': {
      id: '/guide/installation'
      path: '/installation'
      fullPath: '/guide/installation'
      preLoaderRoute: typeof GuideInstallationRouteImport
      parentRoute: typeof GuideRouteRoute
    }
    '/guide/theming': {
      id: '/guide/theming'
      path: '/theming'
      fullPath: '/guide/theming'
      preLoaderRoute: typeof GuideThemingRouteImport
      parentRoute: typeof GuideRouteRoute
    }
  }
}

interface ComponentsRouteRouteChildren {
  ComponentsAccordionRoute: typeof ComponentsAccordionRoute
  ComponentsAlertRoute: typeof ComponentsAlertRoute
  ComponentsAspectRatioRoute: typeof ComponentsAspectRatioRoute
  ComponentsAvatarRoute: typeof ComponentsAvatarRoute
  ComponentsBadgeRoute: typeof ComponentsBadgeRoute
  ComponentsButtonRoute: typeof ComponentsButtonRoute
  ComponentsCardRoute: typeof ComponentsCardRoute
  ComponentsCarouselRoute: typeof ComponentsCarouselRoute
  ComponentsCenterRoute: typeof ComponentsCenterRoute
  ComponentsCheckboxRoute: typeof ComponentsCheckboxRoute
  ComponentsClusterRoute: typeof ComponentsClusterRoute
  ComponentsCollapsibleRoute: typeof ComponentsCollapsibleRoute
  ComponentsCommandRoute: typeof ComponentsCommandRoute
  ComponentsContainerRoute: typeof ComponentsContainerRoute
  ComponentsDialogRoute: typeof ComponentsDialogRoute
  ComponentsDropdownMenuRoute: typeof ComponentsDropdownMenuRoute
  ComponentsFieldRoute: typeof ComponentsFieldRoute
  ComponentsGridRoute: typeof ComponentsGridRoute
  ComponentsHoverCardRoute: typeof ComponentsHoverCardRoute
  ComponentsInputRoute: typeof ComponentsInputRoute
  ComponentsLabelRoute: typeof ComponentsLabelRoute
  ComponentsPopoverRoute: typeof ComponentsPopoverRoute
  ComponentsProgressRoute: typeof ComponentsProgressRoute
  ComponentsRadioGroupRoute: typeof ComponentsRadioGroupRoute
  ComponentsSectionRoute: typeof ComponentsSectionRoute
  ComponentsSelectRoute: typeof ComponentsSelectRoute
  ComponentsSeparatorRoute: typeof ComponentsSeparatorRoute
  ComponentsSkeletonRoute: typeof ComponentsSkeletonRoute
  ComponentsSpacerRoute: typeof ComponentsSpacerRoute
  ComponentsSplitRoute: typeof ComponentsSplitRoute
  ComponentsStackRoute: typeof ComponentsStackRoute
  ComponentsSwitchRoute: typeof ComponentsSwitchRoute
  ComponentsTableRoute: typeof ComponentsTableRoute
  ComponentsTabsRoute: typeof ComponentsTabsRoute
  ComponentsTextareaRoute: typeof ComponentsTextareaRoute
  ComponentsToastRoute: typeof ComponentsToastRoute
  ComponentsTooltipRoute: typeof ComponentsTooltipRoute
  ComponentsIndexRoute: typeof ComponentsIndexRoute
}

const ComponentsRouteRouteChildren: ComponentsRouteRouteChildren = {
  ComponentsAccordionRoute: ComponentsAccordionRoute,
  ComponentsAlertRoute: ComponentsAlertRoute,
  ComponentsAspectRatioRoute: ComponentsAspectRatioRoute,
  ComponentsAvatarRoute: ComponentsAvatarRoute,
  ComponentsBadgeRoute: ComponentsBadgeRoute,
  ComponentsButtonRoute: ComponentsButtonRoute,
  ComponentsCardRoute: ComponentsCardRoute,
  ComponentsCarouselRoute: ComponentsCarouselRoute,
  ComponentsCenterRoute: ComponentsCenterRoute,
  ComponentsCheckboxRoute: ComponentsCheckboxRoute,
  ComponentsClusterRoute: ComponentsClusterRoute,
  ComponentsCollapsibleRoute: ComponentsCollapsibleRoute,
  ComponentsCommandRoute: ComponentsCommandRoute,
  ComponentsContainerRoute: ComponentsContainerRoute,
  ComponentsDialogRoute: ComponentsDialogRoute,
  ComponentsDropdownMenuRoute: ComponentsDropdownMenuRoute,
  ComponentsFieldRoute: ComponentsFieldRoute,
  ComponentsGridRoute: ComponentsGridRoute,
  ComponentsHoverCardRoute: ComponentsHoverCardRoute,
  ComponentsInputRoute: ComponentsInputRoute,
  ComponentsLabelRoute: ComponentsLabelRoute,
  ComponentsPopoverRoute: ComponentsPopoverRoute,
  ComponentsProgressRoute: ComponentsProgressRoute,
  ComponentsRadioGroupRoute: ComponentsRadioGroupRoute,
  ComponentsSectionRoute: ComponentsSectionRoute,
  ComponentsSelectRoute: ComponentsSelectRoute,
  ComponentsSeparatorRoute: ComponentsSeparatorRoute,
  ComponentsSkeletonRoute: ComponentsSkeletonRoute,
  ComponentsSpacerRoute: ComponentsSpacerRoute,
  ComponentsSplitRoute: ComponentsSplitRoute,
  ComponentsStackRoute: ComponentsStackRoute,
  ComponentsSwitchRoute: ComponentsSwitchRoute,
  ComponentsTableRoute: ComponentsTableRoute,
  ComponentsTabsRoute: ComponentsTabsRoute,
  ComponentsTextareaRoute: ComponentsTextareaRoute,
  ComponentsToastRoute: ComponentsToastRoute,
  ComponentsTooltipRoute: ComponentsTooltipRoute,
  ComponentsIndexRoute: ComponentsIndexRoute,
}

const ComponentsRouteRouteWithChildren = ComponentsRouteRoute._addFileChildren(
  ComponentsRouteRouteChildren,
)

interface GuideRouteRouteChildren {
  GuideCliRoute: typeof GuideCliRoute
  GuideGettingStartedRoute: typeof GuideGettingStartedRoute
  GuideInstallationRoute: typeof GuideInstallationRoute
  GuideThemingRoute: typeof GuideThemingRoute
  GuideIndexRoute: typeof GuideIndexRoute
}

const GuideRouteRouteChildren: GuideRouteRouteChildren = {
  GuideCliRoute: GuideCliRoute,
  GuideGettingStartedRoute: GuideGettingStartedRoute,
  GuideInstallationRoute: GuideInstallationRoute,
  GuideThemingRoute: GuideThemingRoute,
  GuideIndexRoute: GuideIndexRoute,
}

const GuideRouteRouteWithChildren = GuideRouteRoute._addFileChildren(
  GuideRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComponentsRouteRoute: ComponentsRouteRouteWithChildren,
  GuideRouteRoute: GuideRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
